import type { Metadata } from 'next';
import { fetchSpecOnServer } from '@/lib/serverSpec';
import OpenAPIViewer from '@/components/OpenAPIViewer';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getServiceById } from '@/lib/services';

type Props = {
    params: Promise<{ service: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { service: serviceId } = await params;
    const service = getServiceById(serviceId);

    if (!service) {
        return notFound();
    }

    try {
        const spec = await fetchSpecOnServer(service.schemaUrl);
        return {
            title: spec.info.title,
            description: spec.info.description || `API documentation for ${spec.info.title}`,
            openGraph: {
                title: spec.info.title,
                description: spec.info.description || `API documentation for ${spec.info.title}`,
                type: 'website'
            },
            twitter: {
                card: 'summary_large_image',
                title: spec.info.title,
                description: spec.info.description || `API documentation for ${spec.info.title}`
            }
        };
    } catch (error) {
        return {
            title: service.name || 'API Documentation',
            description: 'API documentation'
        };
    }
}

export default async function ServicePage({ params }: Props) {
    const { service: serviceId } = await params;
    const service = getServiceById(serviceId);

    if (!service) {
        return notFound();
    }

    return (
        <OpenAPIViewer
            source={service.schemaUrl}
            authentication={{
                fields: [
                    { type: 'password', label: 'Password', placeholder: 'Enter your password' }
                ]
            }}
            theme={process.env.THEME as 'light' | 'dark' | 'system' || 'system'}
            company={<span>Generated by <Link href="https://sunbi.com.np" className="underline" target='_blank'>SunBi</Link></span>}
        />
    );
}
